"""CREATE: tables.

Revision ID: 50f8f0742c91
Revises: 
Create Date: 2026-05-19 15:00:46.681967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50f8f0742c91'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('integration_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system', sa.String(length=50), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shift_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shift_order_id', sa.String(length=100), nullable=False),
    sa.Column('patient_name', sa.String(length=255), nullable=False),
    sa.Column('patient_document', sa.String(length=50), nullable=True),
    sa.Column('doctor_name', sa.String(length=255), nullable=True),
    sa.Column('insurance_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shift_order_id')
    )
    op.create_table('webhook_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aplis_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shift_order_id', sa.Integer(), nullable=False),
    sa.Column('aplis_request_code', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('response_payload', sa.JSON(), nullable=True),
    sa.Column('pdf_base64', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['shift_order_id'], ['shift_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aplis_request_code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aplis_requests')
    op.drop_table('webhook_events')
    op.drop_table('shift_orders')
    op.drop_table('integration_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
